/* tslint:disable */
/* eslint-disable */
/**
 * API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogInDTO
 */
export interface LogInDTO {
    /**
     * 
     * @type {number}
     * @memberof LogInDTO
     */
    userType?: number;
    /**
     * 
     * @type {string}
     * @memberof LogInDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogInDTO
     */
    password?: string | null;
}

/**
 * Check if a given object implements the LogInDTO interface.
 */
export function instanceOfLogInDTO(value: object): value is LogInDTO {
    return true;
}

export function LogInDTOFromJSON(json: any): LogInDTO {
    return LogInDTOFromJSONTyped(json, false);
}

export function LogInDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogInDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userType': json['userType'] == null ? undefined : json['userType'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function LogInDTOToJSON(value?: LogInDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userType': value['userType'],
        'email': value['email'],
        'password': value['password'],
    };
}

