/* tslint:disable */
/* eslint-disable */
/**
 * API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpDTO
 */
export interface SignUpDTO {
    /**
     * 
     * @type {number}
     * @memberof SignUpDTO
     */
    userType?: number;
    /**
     * 
     * @type {string}
     * @memberof SignUpDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SignUpDTO
     */
    studentId?: number;
    /**
     * 
     * @type {string}
     * @memberof SignUpDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignUpDTO
     */
    password?: string | null;
}

/**
 * Check if a given object implements the SignUpDTO interface.
 */
export function instanceOfSignUpDTO(value: object): value is SignUpDTO {
    return true;
}

export function SignUpDTOFromJSON(json: any): SignUpDTO {
    return SignUpDTOFromJSONTyped(json, false);
}

export function SignUpDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'userType': json['userType'] == null ? undefined : json['userType'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'studentId': json['studentId'] == null ? undefined : json['studentId'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function SignUpDTOToJSON(value?: SignUpDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userType': value['userType'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'studentId': value['studentId'],
        'email': value['email'],
        'password': value['password'],
    };
}

