/* tslint:disable */
/* eslint-disable */
/**
 * API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamDTO
 */
export interface TeamDTO {
    /**
     * 
     * @type {string}
     * @memberof TeamDTO
     */
    teamName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamDTO
     */
    teacherName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamDTO
     */
    groupName?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TeamDTO
     */
    studentList?: Array<string> | null;
}

/**
 * Check if a given object implements the TeamDTO interface.
 */
export function instanceOfTeamDTO(value: object): value is TeamDTO {
    return true;
}

export function TeamDTOFromJSON(json: any): TeamDTO {
    return TeamDTOFromJSONTyped(json, false);
}

export function TeamDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'teamName': json['teamName'] == null ? undefined : json['teamName'],
        'teacherName': json['teacherName'] == null ? undefined : json['teacherName'],
        'groupName': json['groupName'] == null ? undefined : json['groupName'],
        'studentList': json['studentList'] == null ? undefined : json['studentList'],
    };
}

export function TeamDTOToJSON(value?: TeamDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teamName': value['teamName'],
        'teacherName': value['teacherName'],
        'groupName': value['groupName'],
        'studentList': value['studentList'],
    };
}

