/* tslint:disable */
/* eslint-disable */
/**
 * API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LogInDTO,
  SignUpDTO,
} from '../models/index';
import {
    LogInDTOFromJSON,
    LogInDTOToJSON,
    SignUpDTOFromJSON,
    SignUpDTOToJSON,
} from '../models/index';

export interface ApiAuthentificationLogInPostRequest {
    logInDTO?: LogInDTO;
}

export interface ApiAuthentificationSignUpPostRequest {
    signUpDTO?: SignUpDTO;
}

/**
 * 
 */
export class AuthentificationApi extends runtime.BaseAPI {

    /**
     */
    async apiAuthentificationLogInPostRaw(requestParameters: ApiAuthentificationLogInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Authentification/LogIn`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogInDTOToJSON(requestParameters['logInDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthentificationLogInPost(requestParameters: ApiAuthentificationLogInPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthentificationLogInPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiAuthentificationLogOutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Authentification/LogOut`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthentificationLogOutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthentificationLogOutPostRaw(initOverrides);
    }

    /**
     */
    async apiAuthentificationSignUpPostRaw(requestParameters: ApiAuthentificationSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Authentification/SignUp`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignUpDTOToJSON(requestParameters['signUpDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAuthentificationSignUpPost(requestParameters: ApiAuthentificationSignUpPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthentificationSignUpPostRaw(requestParameters, initOverrides);
    }

}
