name: Build and Publish Server Docker Image

on:
  push:
    branches: ["main", "build-docker-server"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './CodebustersPAS-Server'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/pas-codebusters-server:latest
        file: ./Dockerfile

    - name: Log out from Docker Hub
      run: docker logout